/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Nalaz;

import Nalaz_Pretraga.uvezivanje;
import OsnovneKlase.Nalaz;
import OsnovneKlase.Pacijent;
import OsnovneKlase.Pretraga;
import database.NalazKontroler;
import database.Pacijent_Kontroler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class dodavanjeNalaza extends javax.swing.JInternalFrame {

    /**
     * Creates new form dodavanjeNalaza
     */
    public dodavanjeNalaza() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nazivNalaza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Unesite potrebne podatke za odradeni nalaz");

        jLabel2.setText("Naziv nalaza");

        jLabel3.setText("Pacijent_ID");

        jLabel4.setText("Datum ");

        jButton1.setText("DODAJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(112, 112, 112)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nazivNalaza)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nazivNalaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        try {
        NalazKontroler nalazKontroler = new NalazKontroler();
        Pacijent_Kontroler pacijentKontroler = new Pacijent_Kontroler();

        String naziv = nazivNalaza.getText().trim();
        String datum = jTextField2.getText().trim();
        String pacijentIdText = jTextField1.getText().trim();

        if (naziv.isEmpty() || datum.isEmpty() || pacijentIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite vrijednost u sva polja jer inace program ne moze raditi.");
            return;
        }

        int idPacijenta = Integer.parseInt(pacijentIdText);

        Pacijent pacijent = pacijentKontroler.nadjiPacijentaPoId(idPacijenta);
        if (pacijent == null) {
            JOptionPane.showMessageDialog(this, "Ne mozemo pronaci tog pacijenta.");
            return;
        }

        Nalaz nalaz = new Nalaz(naziv, datum, idPacijenta);

        int noviId = nalazKontroler.generisiIdNalaza();
        nalaz.setIdNalaza(noviId);

        nalazKontroler.dodajNalaz(nalaz);

        JOptionPane.showMessageDialog(this, "Nalaz uspješno dodat!");

        nazivNalaza.setText("");
        jTextField2.setText("");
        jTextField1.setText("");
        
        uvezivanje uvezivanjeProzor = new uvezivanje(noviId);
        this.getDesktopPane().add(uvezivanjeProzor);
        uvezivanjeProzor.setVisible(true);


    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID je broj.");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Greska: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed
    public void setPacijentId(int idPacijenta) {
    jTextField1.setText(String.valueOf(idPacijenta));
    jTextField1.setEditable(false); 
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nazivNalaza;
    // End of variables declaration//GEN-END:variables
}
