/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Nalaz;

import OsnovneKlase.Nalaz;
import database.NalazKontroler;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Korisnik
 */
public class pregledSvihNalaza extends javax.swing.JInternalFrame {

    /**
     * Creates new form pregledSvihNalaza
     */
    public pregledSvihNalaza() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        setClosable(true);
    }
            
    public void postaviModeleNalaza(javax.swing.table.DefaultTableModel model) {
    jTable1.setModel(model);
}
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Pacijent_ID", "Datum", "Naziv"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PREGLED PRETRAGA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Molimo vas da odaberete nalaz iz tabele.");
    return;
    }

    int nalazId = (int) jTable1.getValueAt(selectedRow, 0);

    try {
        java.sql.Connection conn = new NalazKontroler().getKon();
        String sql = "SELECT p.naziv, np.IzmjereneVrijednosti "
                   + "FROM Nalaz_Pretraga np "
                   + "INNER JOIN Pretraga p ON np.Pretraga_ID = p.naziv "
                   + "WHERE np.Nalaza_ID = ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, nalazId);

        java.sql.ResultSet rs = ps.executeQuery();
        StringBuilder poruka = new StringBuilder();

        while (rs.next()) {
            String naziv = rs.getString("naziv");
            double izmjerena = rs.getDouble("IzmjereneVrijednosti");
            poruka.append("- ").append(naziv).append(": ").append(izmjerena).append("\n");
        }

        if (poruka.length() == 0) {
            poruka.append("Nema pretraga za odabrani nalaz.");
        }

        javax.swing.JOptionPane.showMessageDialog(this, poruka.toString(), "Pretrage nalaza", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        rs.close();
        ps.close();
        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Greška pri dohvatanju pretraga: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
