/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Nalaz_Pretraga;

import OsnovneKlase.NalazPretraga;
import database.NalazPretraga_Kontroler;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import OsnovneKlase.NalazPretraga;


/**
 *
 * @author Korisnik
 */
public class brisanjeVeze extends javax.swing.JInternalFrame {

    /**
     * Creates new form brisanjeVeze
     */
    public brisanjeVeze() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        setClosable(true);
        ucitajTabelu();
    }
    
private void ucitajTabelu() {
    NalazPretraga_Kontroler kontroler = new NalazPretraga_Kontroler();
    List<OsnovneKlase.NalazPretraga> lista = kontroler.getSveNalazPretrage();

    String[] kolone = {"ID_VEZE", "Nalaza_ID", "Pretraga_ID", "IzmjereneVrijednosti"};
    Object[][] podaci = new Object[lista.size()][4];

    for (int i = 0; i < lista.size(); i++) {
        OsnovneKlase.NalazPretraga np = lista.get(i);
        podaci[i][0] = np.getId();
        podaci[i][1] = np.getNalazId();
        podaci[i][2] = np.getPretragaId();
        podaci[i][3] = np.getIzmjereneVrijednosti();
    }

    jTable1.setModel(new javax.swing.table.DefaultTableModel(podaci, kolone));
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Kliknite na red kojeg želite obrisati te potvrdite akciju ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_VEZE", "Nalaza_ID", "Pretraga_ID", "IzmjereneVrijednosti"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OBRISI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(205, 205, 205))
                        .addComponent(jScrollPane1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    int red = jTable1.getSelectedRow();
    if (red == -1) {
        JOptionPane.showMessageDialog(this, "Molimo vas da odaberete red za brisanje.");
        return;
    }

    int potvrda = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite obrisati?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
    if (potvrda != JOptionPane.YES_OPTION) {
        return;
    }

    int idVeze = (int) jTable1.getValueAt(red, 0);
    NalazPretraga_Kontroler kontroler = new NalazPretraga_Kontroler();
    boolean uspjeh = kontroler.obrisiNalazPretraga(idVeze);

    if (uspjeh) {
        JOptionPane.showMessageDialog(this, "Zapis uspješno obrisan.");
        ucitajTabelu(); 
    } else {
        JOptionPane.showMessageDialog(this, "Greška prilikom brisanja zapisa.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
