package Nalaz_Pretraga;

import OsnovneKlase.Pretraga;
import database.NalazPretraga_Kontroler;
import database.Pretraga_Kontroler;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Korisnik
 */
public class uvezivanje extends javax.swing.JInternalFrame {

    /**
     * Creates new form uvezivanje
     */
    public uvezivanje(int noviId) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        setClosable(true);
        idNalaza.setText(String.valueOf(noviId));
        idNalaza.setEditable(false); 
        setResizable(true);
        ucitajPretrage();
        jTable1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    }

    public uvezivanje() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 245, 255));
        setClosable(true);
    }
    
        private void ucitajPretrage() {
        Pretraga_Kontroler kontroler = new Pretraga_Kontroler();
        List<Pretraga> pretrage = null;
        try {
            pretrage = kontroler.svePretrage();
        } catch (SQLException ex) {
            System.out.println("Greska "+ ex.getMessage());
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        for (Pretraga p : pretrage) {
            model.addRow(new Object[] { p.getNaziv(), p.getRefVrijednosti() });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        refVr1 = new javax.swing.JTextField();
        refVr2 = new javax.swing.JTextField();
        refvr3 = new javax.swing.JTextField();
        dodaj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idNalaza = new javax.swing.JTextField();

        jLabel1.setText("Za unijeti nalaz izaberi minimalno 1 a maksimalno 3 pretrage");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Naziv", "ReferentnaVrijednost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Unesi izmjerenu vrijednost za prvu odradenu pretragu");

        jLabel3.setText("Unesi izmjerenu vrijednost za drugu odradenu pretragu");

        jLabel4.setText("Unesi izmjerenu vrijednost za trecu odradenu pretragu");

        refVr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refVr1ActionPerformed(evt);
            }
        });

        dodaj.setBackground(new java.awt.Color(51, 51, 255));
        dodaj.setForeground(new java.awt.Color(255, 255, 255));
        dodaj.setText("DODAJ");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        jLabel5.setText("Unesite ID nalaza");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(refVr1)
                                    .addComponent(refVr2)
                                    .addComponent(refvr3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(81, 81, 81)
                                        .addComponent(idNalaza, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idNalaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(refVr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(refVr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(refvr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refVr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refVr1ActionPerformed

    }//GEN-LAST:event_refVr1ActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed

        int[] odabraniRedovi = jTable1.getSelectedRows();

        if (odabraniRedovi.length == 0 || odabraniRedovi.length > 3) {
            JOptionPane.showMessageDialog(this, "Odaberite minimalno 1 a maksimalno 3 pretrage.");
            return;
        }

        String idNalazaText = idNalaza.getText().trim();
        if (idNalazaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite ID nalaza.");
            return;
        }

        int idNalaza;
        
        try {
            idNalaza = Integer.parseInt(idNalazaText);
            database.NalazKontroler nalazKontroler = new database.NalazKontroler();
        boolean postoji = false;
        
        try {
        postoji = nalazKontroler.postojiNalaz(idNalaza);
        } catch (SQLException ex) {
        Logger.getLogger(uvezivanje.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Greška pri provjeri nalaza: " + ex.getMessage());
        return;
        }

        if (!postoji) {
            JOptionPane.showMessageDialog(this, "Nalaz sa unesenim ID-jem ne postoji u bazi.");
            return;
        }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID nalaza mora biti broj.");
            return;
        }

        String[] vrijednosti = new String[] {
            refVr1.getText().trim(),
            refVr2.getText().trim(),
            refvr3.getText().trim()
        };

        NalazPretraga_Kontroler kontroler = new NalazPretraga_Kontroler();

        try {
            for (int i = 0; i < odabraniRedovi.length; i++) {
                String nazivPretrage = jTable1.getValueAt(odabraniRedovi[i], 0).toString();
                String izmjerenaVrijednost = vrijednosti[i];

                if (izmjerenaVrijednost.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Unesite sve izmjerene vrijednosti.");
                    return;
                }

                kontroler.dodajNalazPretraga(idNalaza, nazivPretrage, izmjerenaVrijednost);
            }

            JOptionPane.showMessageDialog(this, "Uspješno dodano u bazu.");

            refVr1.setText("");
            refVr2.setText("");
            refvr3.setText("");
            jTable1.clearSelection();

            }catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greška pri unosu u bazu: " + ex.getMessage());
            }

    }//GEN-LAST:event_dodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JTextField idNalaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField refVr1;
    private javax.swing.JTextField refVr2;
    private javax.swing.JTextField refvr3;
    // End of variables declaration//GEN-END:variables
}
